
·`
"May 2025 Week 1 Schedule.xlsx.jsonapplication/json®`{
  "id": "sheet_70c4bd2f55f34effc7562fdf01cb9e6c",
  "driveId": "",
  "name": "May 2025 Week 1 Schedule.xlsx",
  "mimeType": "application/vnd.google-apps.spreadsheet",
  "createdTime": "2025-07-21T17:50:50Z",
  "modifiedTime": "2025-05-01T23:56:48Z",
  "parents": [],
  "owners": [
    "john.doe@gmail.com"
  ],
  "size": 0,
  "trashed": false,
  "starred": false,
  "properties": {
    "title": "May 2025 Week 1 Schedule",
    "locale": "en_US",
    "timeZone": "UTC"
  },
  "sheets": [
    {
      "properties": {
        "sheetId": 1,
        "title": "May 1st",
        "index": 0,
        "sheetType": "GRID",
        "gridProperties": {
          "rowCount": 1000,
          "columnCount": 26
        }
      }
    },
    {
      "properties": {
        "sheetId": 2,
        "title": "May 2nd",
        "index": 1,
        "sheetType": "GRID",
        "gridProperties": {
          "rowCount": 1000,
          "columnCount": 26
        }
      }
    },
    {
      "properties": {
        "sheetId": 3,
        "title": "May 3rd",
        "index": 2,
        "sheetType": "GRID",
        "gridProperties": {
          "rowCount": 1000,
          "columnCount": 26
        }
      }
    }
  ],
  "data": {
    "May 1st!A1:Z9": [
      [
        "Time",
        "Customer Name",
        "Vehicle",
        "Service",
        "Technician",
        "Notes",
        "Column 1",
        "Column 2",
        "Column 3",
        "Column 4",
        "Column 5",
        "Column 6",
        "Column 7",
        "Column 8",
        "Column 9",
        "Column 10",
        "Column 11",
        "Column 12",
        "Column 13",
        "Column 14",
        "Column 15",
        "Column 16",
        "Column 17",
        "Column 18",
        "Column 19",
        "Column 20"
      ],
      [
        "08:00:00",
        "John Smith",
        "Toyota Camry",
        "Oil Change, Tire Rotation",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "09:00:00",
        "Mary Brown",
        "Honda Accord",
        "Brake Replacement",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "10:00:00",
        "Angela Garcia",
        "Ford F-150",
        "Collision Repair (Estimate)",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "11:00:00",
        "Brian Martinez",
        "Chevy Silverado",
        "AC Repair",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "13:00:00",
        "Kevin Thomas",
        "BMW 3 Series",
        "Scheduled Maintenance",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "14:00:00",
        "Sarah Jackson",
        "Subaru Outback",
        "Tire Replacement",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "15:00:00",
        "Anthony White",
        "Jeep Wrangler",
        "Diagnostic Check",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "16:00:00",
        "Michelle Harris",
        "Mercedes-Benz C-Class",
        "Oil Change",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    ],
    "May 2nd!A1:Z9": [
      [
        "Time",
        "Customer Name",
        "Vehicle",
        "Service",
        "Technician",
        "Notes",
        "Column 1",
        "Column 2",
        "Column 3",
        "Column 4",
        "Column 5",
        "Column 6",
        "Column 7",
        "Column 8",
        "Column 9",
        "Column 10",
        "Column 11",
        "Column 12",
        "Column 13",
        "Column 14",
        "Column 15",
        "Column 16",
        "Column 17",
        "Column 18",
        "Column 19",
        "Column 20"
      ],
      [
        "08:00:00",
        "Joseph Hayes",
        "Toyota Camry",
        "Oil Change, Tire Rotation",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "09:00:00",
        "Raymond Davis",
        "Honda Accord",
        "Brake Replacement",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "10:00:00",
        "Robert Jones",
        "Ford F-150",
        "AC Repair",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "11:00:00",
        "Mary Brown",
        "Chevy Silverado",
        "Diagnostic Check",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "13:00:00",
        "Michael Davis",
        "BMW 3 Series",
        "Scheduled Maintenance",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "14:00:00",
        "Jennifer Wilson",
        "Subaru Outback",
        "Tire Replacement",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "15:00:00",
        "David Garcia",
        "Jeep Wrangler",
        "Collision Repair (Estimate)",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "16:00:00",
        "Linda Rodriguez",
        "Mercedes-Benz C-Class",
        "Oil Change",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    ],
    "May 3rd!A1:Z9": [
      [
        "Time",
        "Customer Name",
        "Vehicle",
        "Service",
        "Technician",
        "Notes",
        "Column 1",
        "Column 2",
        "Column 3",
        "Column 4",
        "Column 5",
        "Column 6",
        "Column 7",
        "Column 8",
        "Column 9",
        "Column 10",
        "Column 11",
        "Column 12",
        "Column 13",
        "Column 14",
        "Column 15",
        "Column 16",
        "Column 17",
        "Column 18",
        "Column 19",
        "Column 20"
      ],
      [
        "08:00:00",
        "Carolyn Garcia",
        "Toyota Rav4",
        "Oil Change, Synthetic",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "09:00:00",
        "Steve Wilson",
        "Honda Odessey",
        "Tire Rotation",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "10:00:00",
        "Jean Rodriguez",
        "Ford Fusion",
        "AC Repair (Diagnostic)",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "11:00:00",
        "Mary Brown",
        "Chevy Silverado",
        "Diagnostic Check",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "13:00:00",
        "Michael Davis",
        "Subaru Outback",
        "Alignment",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "14:00:00",
        "Paul Hall",
        "Fiat 500",
        "Oil Change, Synthetic",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "15:00:00",
        "Grace Williams",
        "Kia Sorento",
        "Collision Repair (Estimate)",
        "Dave",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "16:00:00",
        "Aaron Wilson",
        "Scion XB",
        "Oil Change, Standard",
        "Otto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    ]
  },
  "permissions": [
    {
      "id": "permission_sheet_70c4bd2f55f34effc7562fdf01cb9e6c",
      "role": "owner",
      "type": "user",
      "emailAddress": "john.doe@gmail.com"
    }
  ]
}
Ë
 Summer Email Promotion.docx.jsonapplication/json±{
  "id": "file_ed4061db03cbaefe2e288ebc1e0b7410",
  "driveId": "",
  "name": "Summer Email Promotion.docx",
  "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "createdTime": "2025-07-21T17:50:48Z",
  "modifiedTime": "2025-05-01T22:07:02Z",
  "trashed": false,
  "starred": false,
  "parents": [],
  "owners": [
    "john.doe@gmail.com"
  ],
  "size": "1006279",
  "permissions": [
    {
      "id": "permission_file_ed4061db03cbaefe2e288ebc1e0b7410",
      "role": "owner",
      "type": "user",
      "emailAddress": "john.doe@gmail.com"
    }
  ],
  "suggestionsViewMode": "DEFAULT",
  "includeTabsContent": false,
  "tabs": [],
  "content": [
    {
      "elementId": "p1",
      "text": "Subject: Ô∏è Beat the Heat! 20% Off AC Repair!"
    },
    {
      "elementId": "p2",
      "text": "Body:"
    },
    {
      "elementId": "p3",
      "text": "Hi [Customer Name],"
    },
    {
      "elementId": "p4",
      "text": "Don't let the summer heat get the best of you! Is your car's AC blowing hot air? Get it fixed now and stay cool all season long."
    },
    {
      "elementId": "p5",
      "text": "For a limited time, Otto's Auto Body and Collision Repair is offering 20% OFF on all AC repair services!"
    },
    {
      "elementId": "p6",
      "text": "Our expert technicians will:"
    },
    {
      "elementId": "p7",
      "text": "Diagnose the problem"
    },
    {
      "elementId": "p8",
      "text": "Repair any issues"
    },
    {
      "elementId": "p9",
      "text": "Get your AC running ice-cold"
    },
    {
      "elementId": "p10",
      "text": "This offer is valid until August 31st, so schedule your appointment today!"
    },
    {
      "elementId": "p11",
      "text": "[Link to Schedule Appointment]"
    },
    {
      "elementId": "p12",
      "text": "Or call us at 555-123-4567"
    },
    {
      "elementId": "p13",
      "text": "Sincerely,"
    },
    {
      "elementId": "p14",
      "text": "The Team at Otto's Auto Body and Collision Repair"
    }
  ],
  "revisions": [
    {
      "id": "rev-1",
      "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "modifiedTime": "2025-05-01T22:07:02Z",
      "keepForever": false,
      "originalFilename": "Summer Email Promotion.docx",
      "size": "1006279"
    }
  ]
}
À
:Otto_s Auto Body and Collision Repair-Price List.docx.jsonapplication/json˙{
  "id": "file_c82fc48e5e6d7f7f1224810a2bb41570",
  "driveId": "",
  "name": "Otto_s Auto Body and Collision Repair-Price List.docx",
  "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "createdTime": "2025-07-21T17:50:50Z",
  "modifiedTime": "2025-05-02T00:31:45Z",
  "trashed": false,
  "starred": false,
  "parents": [],
  "owners": [
    "john.doe@gmail.com"
  ],
  "size": "7496",
  "permissions": [
    {
      "id": "permission_file_c82fc48e5e6d7f7f1224810a2bb41570",
      "role": "owner",
      "type": "user",
      "emailAddress": "john.doe@gmail.com"
    }
  ],
  "suggestionsViewMode": "DEFAULT",
  "includeTabsContent": false,
  "tabs": [],
  "content": [
    {
      "elementId": "p1",
      "text": "Otto's Auto Body and Collision Repair - Price List"
    },
    {
      "elementId": "t1",
      "text": "Service | Price\nOil Change (Standard) | $70\nOil Change (Synthetic) | $100\nTire Rotation | $50\nBrake Replacement (per axle) | $300 - $450\nAC Repair (Diagnostic) | $150\nAC Repair (Full Repair) | $200 - $1000\nScheduled Maintenance (Minor) | $150 - $300\nScheduled Maintenance (Major) | $400 - $700\nTire Replacement (per tire) | $100 - $300\nDiagnostic Check | $100\nCollision Repair (Estimate) | Free\nBattery Replacement | $150 - $300\nAlignment | $120"
    }
  ],
  "revisions": [
    {
      "id": "rev-1",
      "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "modifiedTime": "2025-05-02T00:31:45Z",
      "keepForever": false,
      "originalFilename": "Otto_s Auto Body and Collision Repair-Price List.docx",
      "size": "7496"
    }
  ]
}
É
Invoice 46375.docx.jsonapplication/json’{
  "id": "file_17442a507879b845482e5ee62464be23",
  "driveId": "",
  "name": "Invoice 46375.docx",
  "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "createdTime": "2025-07-21T17:50:50Z",
  "modifiedTime": "2025-05-01T23:32:18Z",
  "trashed": false,
  "starred": false,
  "parents": [],
  "owners": [
    "john.doe@gmail.com"
  ],
  "size": "8597",
  "permissions": [
    {
      "id": "permission_file_17442a507879b845482e5ee62464be23",
      "role": "owner",
      "type": "user",
      "emailAddress": "john.doe@gmail.com"
    }
  ],
  "suggestionsViewMode": "DEFAULT",
  "includeTabsContent": false,
  "tabs": [],
  "content": [
    {
      "elementId": "p1",
      "text": "Otto's Auto Body and Collision Repair 123 Main St Moosetown, OR 12345 (555) 123-4567 https://www.google.com/search?q=https://www.ottosauto.com"
    },
    {
      "elementId": "p2",
      "text": "Invoice"
    },
    {
      "elementId": "p3",
      "text": "Invoice #: 46375 Date: 05/01/2025 Time: 12:47 PM"
    },
    {
      "elementId": "p4",
      "text": "Customer: Brian Martinez 555-345-6789 brian.martinez@email.com"
    },
    {
      "elementId": "p5",
      "text": "Vehicle: Chevy Silverado"
    },
    {
      "elementId": "p6",
      "text": "Mechanic: Dave"
    },
    {
      "elementId": "p7",
      "text": "Service: AC Repair"
    },
    {
      "elementId": "p8",
      "text": "Notes:"
    },
    {
      "elementId": "p9",
      "text": "36-month warranty on compressor"
    },
    {
      "elementId": "p10",
      "text": "Thank you for your business!"
    },
    {
      "elementId": "p11",
      "text": "Payment Terms: Due upon completion of service. We accept cash, check, and all major credit cards."
    },
    {
      "elementId": "t1",
      "text": "Description | Quantity | Rate | Amount\nDiagnose AC System | 1 | $150.00 | $150.00\nReplace AC Compressor | 1 | $400.00 | $400.00\nRefrigerant Recharge | 1 | $120.00 | $120.00\nLabor: AC Repair | 1.75 hours | $100.00/hour | $175.00\nParts Subtotal |  |  | $670.00\nLabor Subtotal |  |  | $175.00\nTotal Before Discount |  |  | $845\nCustomer Loyalty Status | Silver | 15% off | -126.75\nTotal |  |  | $718.25"
    }
  ],
  "revisions": [
    {
      "id": "rev-1",
      "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "modifiedTime": "2025-05-01T23:32:18Z",
      "keepForever": false,
      "originalFilename": "Invoice 46375.docx",
      "size": "8597"
    }
  ]
}
ó
NOtto_s Auto Body and Collision Repair-Customer Loyalty Program Perks.docx.jsonapplication/json≤{
  "id": "file_c6862801b9f59f2c8626fc490e7d9475",
  "driveId": "",
  "name": "Otto_s Auto Body and Collision Repair-Customer Loyalty Program Perks.docx",
  "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "createdTime": "2025-07-21T17:50:50Z",
  "modifiedTime": "2025-05-02T00:28:52Z",
  "trashed": false,
  "starred": false,
  "parents": [],
  "owners": [
    "john.doe@gmail.com"
  ],
  "size": "7195",
  "permissions": [
    {
      "id": "permission_file_c6862801b9f59f2c8626fc490e7d9475",
      "role": "owner",
      "type": "user",
      "emailAddress": "john.doe@gmail.com"
    }
  ],
  "suggestionsViewMode": "DEFAULT",
  "includeTabsContent": false,
  "tabs": [],
  "content": [
    {
      "elementId": "p1",
      "text": "Otto's Auto Body and Collision Repair - Customer Loyalty Program Perks"
    },
    {
      "elementId": "p2",
      "text": "Here's a breakdown of the discounts and perks offered to customers based on their loyalty status:"
    },
    {
      "elementId": "p3",
      "text": "Bronze:"
    },
    {
      "elementId": "p4",
      "text": "10% off on all services"
    },
    {
      "elementId": "p5",
      "text": "Free car wash with any service"
    },
    {
      "elementId": "p6",
      "text": "Priority scheduling"
    },
    {
      "elementId": "p7",
      "text": "Silver:"
    },
    {
      "elementId": "p8",
      "text": "15% off on all services"
    },
    {
      "elementId": "p9",
      "text": "Free car wash and interior vacuum with any service"
    },
    {
      "elementId": "p10",
      "text": "Free roadside assistance (limited to 2 incidents per year)"
    },
    {
      "elementId": "p11",
      "text": "Priority scheduling"
    },
    {
      "elementId": "p12",
      "text": "Gold:"
    },
    {
      "elementId": "p13",
      "text": "20% off on all services"
    },
    {
      "elementId": "p14",
      "text": "Free car wash and full detailing with any service"
    },
    {
      "elementId": "p15",
      "text": "Free 24/7 roadside assistance (unlimited incidents)"
    },
    {
      "elementId": "p16",
      "text": "Free loaner car for overnight repairs"
    },
    {
      "elementId": "p17",
      "text": "Priority scheduling"
    }
  ],
  "revisions": [
    {
      "id": "rev-1",
      "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "modifiedTime": "2025-05-02T00:28:52Z",
      "keepForever": false,
      "originalFilename": "Otto_s Auto Body and Collision Repair-Customer Loyalty Program Perks.docx",
      "size": "7195"
    }
  ]
}
Î˚
Client List.xlsx.jsonapplication/jsonæ˚{
  "id": "sheet_257b21d75e06410ee7ca5bbb34ead02b",
  "driveId": "",
  "name": "Client List.xlsx",
  "mimeType": "application/vnd.google-apps.spreadsheet",
  "createdTime": "2025-07-21T17:50:48Z",
  "modifiedTime": "2025-05-01T21:32:04Z",
  "parents": [],
  "owners": [
    "john.doe@gmail.com"
  ],
  "size": 0,
  "trashed": false,
  "starred": false,
  "properties": {
    "title": "Client List",
    "locale": "en_US",
    "timeZone": "UTC"
  },
  "sheets": [
    {
      "properties": {
        "sheetId": 1,
        "title": "Client List",
        "index": 0,
        "sheetType": "GRID",
        "gridProperties": {
          "rowCount": 1000,
          "columnCount": 26
        }
      }
    }
  ],
  "data": {
    "Client List!A1:Z74": [
      [
        "Customer Name",
        "Phone Number",
        "Email",
        "Date of First Service",
        "Insurance Provider",
        "Preferred Contact Method",
        "Referral Source",
        "Customer Loyalty Status",
        "Column 1",
        "Column 2",
        "Column 3",
        "Column 4",
        "Column 5",
        "Column 6",
        "Column 7",
        "Column 8",
        "Column 9",
        "Column 10",
        "Column 11",
        "Column 12",
        "Column 13",
        "Column 14",
        "Column 15",
        "Column 16",
        "Column 17",
        "Column 18"
      ],
      [
        "Joseph Hayes",
        "555-543-2108",
        "joseph.hayes@email.com",
        "2022-12-30T00:00:00",
        "Nationwide",
        "Text",
        "Google",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Albert Martinez",
        "555-109-8775",
        "albert.martinez@email.com",
        "2023-01-01T00:00:00",
        "Farmers",
        "Text",
        "Google",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "John Smith",
        "555-123-4567",
        "john.smith@email.com",
        "2023-01-15T00:00:00",
        "State Farm",
        "Phone",
        "Google",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Alice Clark",
        "555-432-1097",
        "alice.clark@email.com",
        "2023-01-15T00:00:00",
        "State Farm",
        "Phone",
        "Website",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Carolyn Garcia",
        "555-098-7664",
        "carolyn.garcia@email.com",
        "2023-01-15T00:00:00",
        "Liberty Mutual",
        "Email",
        "Website",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Robert Young",
        "555-321-0986",
        "robert.young@email.com",
        "2023-02-01T00:00:00",
        "Geico",
        "Email",
        "Walk-in",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Steve Wilson",
        "555-987-6558",
        "steve.wilson@email.com",
        "2023-02-01T00:00:00",
        "Travelers",
        "Phone",
        "Walk-in",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Dorothy King",
        "555-210-9875",
        "dorothy.king@email.com",
        "2023-02-15T00:00:00",
        "Progressive",
        "Text",
        "Referral",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Jean Rodriguez",
        "555-876-5449",
        "jean.rodriguez@email.com",
        "2023-02-15T00:00:00",
        "Nationwide",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Paul Hall",
        "555-109-8764",
        "paul.hall@email.com",
        "2023-03-01T00:00:00",
        "Allstate",
        "Phone",
        "Friend",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Daniel Martinez",
        "555-765-4340",
        "daniel.martinez@email.com",
        "2023-03-01T00:00:00",
        "State Farm",
        "Email",
        "Yelp",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Nancy Wright",
        "555-098-7653",
        "nancy.wright@email.com",
        "2023-03-15T00:00:00",
        "USAA",
        "Email",
        "Yelp",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Jane Doe",
        "555-987-6543",
        "jane.doe@email.com",
        "2023-03-20T00:00:00",
        "Geico",
        "Email",
        "Walk-in",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Raymond Davis",
        "555-987-6540",
        "raymond.davis@email.com",
        "2023-04-01T00:00:00",
        "Farmers",
        "Text",
        "Website",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Evelyn Garcia",
        "555-876-5431",
        "evelyn.garcia@email.com",
        "2023-04-15T00:00:00",
        "Liberty Mutual",
        "Email",
        "Google",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Harold Martinez",
        "555-765-4322",
        "harold.martinez@email.com",
        "2023-05-01T00:00:00",
        "Travelers",
        "Phone",
        "Walk-in",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Robert Jones",
        "555-246-8012",
        "robert.jones@email.com",
        "2023-05-10T00:00:00",
        "Progressive",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Olivia Wilson",
        "555-654-3211",
        "olivia.wilson@email.com",
        "2023-05-15T00:00:00",
        "Nationwide",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Peter Rodriguez",
        "555-543-2100",
        "peter.rodriguez@email.com",
        "2023-06-01T00:00:00",
        "State Farm",
        "Email",
        "Yelp",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Grace Williams",
        "555-432-1099",
        "grace.williams@email.com",
        "2023-06-15T00:00:00",
        "Geico",
        "Phone",
        "Referral",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Mary Brown",
        "555-135-7910",
        "mary.brown@email.com",
        "2023-07-01T00:00:00",
        "Allstate",
        "Phone",
        "Yelp",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Henry Garcia",
        "555-321-0988",
        "henry.garcia@email.com",
        "2023-07-01T00:00:00",
        "Progressive",
        "Text",
        "Google",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Ruth Martinez",
        "555-210-9877",
        "ruth.martinez@email.com",
        "2023-07-15T00:00:00",
        "Allstate",
        "Email",
        "Website",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Earl Wilson",
        "555-109-8766",
        "earl.wilson@email.com",
        "2023-08-01T00:00:00",
        "USAA",
        "Phone",
        "Walk-in",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Sharon Rodriguez",
        "555-098-7655",
        "sharon.rodriguez@email.com",
        "2023-08-15T00:00:00",
        "Farmers",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Ralph Martinez",
        "555-987-6549",
        "ralph.martinez@email.com",
        "2023-09-01T00:00:00",
        "Liberty Mutual",
        "Email",
        "Yelp",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Michael Davis",
        "555-864-2098",
        "michael.davis@email.com",
        "2023-09-12T00:00:00",
        "USAA",
        "Email",
        "Website",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Michelle Garcia",
        "555-876-5440",
        "michelle.garcia@email.com",
        "2023-09-15T00:00:00",
        "Travelers",
        "Phone",
        "Referral",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Aaron Wilson",
        "555-765-4331",
        "aaron.wilson@email.com",
        "2023-10-01T00:00:00",
        "Nationwide",
        "Text",
        "Google",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Doris Rodriguez",
        "555-654-3220",
        "doris.rodriguez@email.com",
        "2023-10-15T00:00:00",
        "State Farm",
        "Email",
        "Website",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Terry Martinez",
        "555-543-2119",
        "terry.martinez@email.com",
        "2023-11-01T00:00:00",
        "Geico",
        "Phone",
        "Walk-in",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Jennifer Wilson",
        "555-753-1967",
        "jennifer.wilson@email.com",
        "2023-11-05T00:00:00",
        "Farmers",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Brenda Garcia",
        "555-432-1108",
        "brenda.garcia@email.com",
        "2023-11-15T00:00:00",
        "Progressive",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Jose Wilson",
        "555-321-1097",
        "jose.wilson@email.com",
        "2023-12-01T00:00:00",
        "Allstate",
        "Email",
        "Yelp",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Kimberly Rodriguez",
        "555-210-9886",
        "kimberly.rodriguez@email.com",
        "2023-12-15T00:00:00",
        "USAA",
        "Phone",
        "Referral",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Eric King",
        "555-345-6791",
        "eric.king@email.com",
        "2024-01-01T00:00:00",
        "Progressive",
        "Email",
        "Walk-in",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Amanda Wright",
        "555-456-7902",
        "amanda.wright@email.com",
        "2024-01-15T00:00:00",
        "Allstate",
        "Phone",
        "Google",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "David Garcia",
        "555-246-9123",
        "david.garcia@email.com",
        "2024-01-18T00:00:00",
        "Liberty Mutual",
        "Phone",
        "Google",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Ryan Green",
        "555-567-9013",
        "ryan.green@email.com",
        "2024-02-01T00:00:00",
        "USAA",
        "Text",
        "Website",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Kimberly Baker",
        "555-678-0124",
        "kimberly.baker@email.com",
        "2024-02-15T00:00:00",
        "Farmers",
        "Email",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Brandon Hall",
        "555-789-1235",
        "brandon.hall@email.com",
        "2024-03-01T00:00:00",
        "Liberty Mutual",
        "Phone",
        "Yelp",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Melissa Adams",
        "555-890-2346",
        "melissa.adams@email.com",
        "2024-03-15T00:00:00",
        "Travelers",
        "Text",
        "Walk-in",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Linda Rodriguez",
        "555-864-5790",
        "linda.rodriguez@email.com",
        "2024-03-22T00:00:00",
        "Travelers",
        "Email",
        "Walk-in",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Justin Nelson",
        "555-901-3457",
        "justin.nelson@email.com",
        "2024-04-01T00:00:00",
        "Nationwide",
        "Email",
        "Google",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Ashley Carter",
        "555-012-4568",
        "ashley.carter@email.com",
        "2024-04-15T00:00:00",
        "State Farm",
        "Phone",
        "Website",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Adam Perez",
        "555-123-5679",
        "adam.perez@email.com",
        "2024-05-01T00:00:00",
        "Geico",
        "Text",
        "Friend",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Christopher Williams",
        "555-135-2689",
        "christopher.williams@email.com",
        "2024-05-08T00:00:00",
        "Nationwide",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Nicole Hayes",
        "555-234-6780",
        "nicole.hayes@email.com",
        "2024-05-15T00:00:00",
        "Progressive",
        "Email",
        "Yelp",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Gary White",
        "555-987-6541",
        "gary.white@email.com",
        "2024-06-01T00:00:00",
        "Allstate",
        "Phone",
        "Referral",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Susan Black",
        "555-876-5432",
        "susan.black@email.com",
        "2024-06-15T00:00:00",
        "USAA",
        "Email",
        "Website",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Timothy Green",
        "555-765-4321",
        "timothy.green@email.com",
        "2024-07-01T00:00:00",
        "Farmers",
        "Text",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Angela Garcia",
        "555-987-5432",
        "angela.garcia@email.com",
        "2024-07-12T00:00:00",
        "State Farm",
        "Phone",
        "Yelp",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Deborah Young",
        "555-654-3210",
        "deborah.young@email.com",
        "2024-07-15T00:00:00",
        "Liberty Mutual",
        "Phone",
        "Google",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Brian Martinez",
        "555-345-6789",
        "brian.martinez@email.com",
        "2024-08-01T00:00:00",
        "Geico",
        "Text",
        "Website",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Ronald Martinez",
        "555-543-2109",
        "ronald.martinez@email.com",
        "2024-08-01T00:00:00",
        "Travelers",
        "Email",
        "Walk-in",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Jessica Anderson",
        "555-456-7890",
        "jessica.anderson@email.com",
        "2024-08-15T00:00:00",
        "Progressive",
        "Email",
        "Friend",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Laura Allen",
        "555-432-1098",
        "laura.allen@email.com",
        "2024-08-15T00:00:00",
        "Nationwide",
        "Text",
        "Referral",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Kevin Thomas",
        "555-567-8901",
        "kevin.thomas@email.com",
        "2024-09-01T00:00:00",
        "Allstate",
        "Phone",
        "Google",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Steven King",
        "555-321-0987",
        "steven.king@email.com",
        "2024-09-01T00:00:00",
        "State Farm",
        "Phone",
        "Yelp",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Sarah Jackson",
        "555-678-9012",
        "sarah.jackson@email.com",
        "2024-09-15T00:00:00",
        "USAA",
        "Text",
        "Yelp",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Catherine Hall",
        "555-210-9876",
        "catherine.hall@email.com",
        "2024-09-15T00:00:00",
        "Geico",
        "Email",
        "Friend",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Anthony White",
        "555-789-0123",
        "anthony.white@email.com",
        "2024-10-01T00:00:00",
        "Farmers",
        "Email",
        "Walk-in",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "James Wright",
        "555-109-8765",
        "james.wright@email.com",
        "2024-10-01T00:00:00",
        "Progressive",
        "Text",
        "Website",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Michelle Harris",
        "555-890-1234",
        "michelle.harris@email.com",
        "2024-10-15T00:00:00",
        "Liberty Mutual",
        "Phone",
        "Friend",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Carolyn Perez",
        "555-098-7654",
        "carolyn.perez@email.com",
        "2024-10-15T00:00:00",
        "Allstate",
        "Phone",
        "Google",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Patrick Lewis",
        "555-901-2345",
        "patrick.lewis@email.com",
        "2024-11-01T00:00:00",
        "Travelers",
        "Text",
        "Google",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Thomas Baker",
        "555-987-6548",
        "thomas.baker@email.com",
        "2024-11-01T00:00:00",
        "USAA",
        "Email",
        "Walk-in",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Nicole Clark",
        "555-012-3456",
        "nicole.clark@email.com",
        "2024-11-15T00:00:00",
        "Nationwide",
        "Email",
        "Website",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Elizabeth Carter",
        "555-876-5439",
        "elizabeth.carter@email.com",
        "2024-11-15T00:00:00",
        "Farmers",
        "Text",
        "Referral",
        "Bronze",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Jason Young",
        "555-123-4560",
        "jason.young@email.com",
        "2024-12-01T00:00:00",
        "State Farm",
        "Phone",
        "Yelp",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "William Adams",
        "555-765-4320",
        "william.adams@email.com",
        "2024-12-01T00:00:00",
        "Liberty Mutual",
        "Phone",
        "Friend",
        "Gold",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Stephanie Hill",
        "555-234-5678",
        "stephanie.hill@email.com",
        "2024-12-15T00:00:00",
        "Geico",
        "Text",
        "Friend",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Betty Perez",
        "555-654-3219",
        "betty.perez@email.com",
        "2024-12-15T00:00:00",
        "Travelers",
        "Email",
        "Yelp",
        "Silver",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    ]
  },
  "permissions": [
    {
      "id": "permission_sheet_257b21d75e06410ee7ca5bbb34ead02b",
      "role": "owner",
      "type": "user",
      "emailAddress": "john.doe@gmail.com"
    }
  ]
}