import json
import os

DB = {
    "CurrentUser": {"id": 1, "login": "octocat"},  # Default to octocat user
    "Users": [
        {
            "login": "octocat",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "name": "The Octocat",
            "email": "octocat@github.com",
            "company": "GitHub",
            "location": "San Francisco",
            "bio": "GitHub's official mascot.",
            "public_repos": 12,
            "public_gists": 10,
            "followers": 9500,
            "following": 9,
            "created_at": "2008-01-14T04:33:35Z",
            "updated_at": "2025-05-10T10:20:30Z",
            "type": "User",
            "score": 1.0,
        },
        {
            "login": "devjane",
            "id": 25,
            "node_id": "MDQ6VXNlcjI1",
            "name": "Jane Developer",
            "email": "jane.dev@example.com",
            "company": "Tech Solutions Inc.",
            "location": "New York, NY",
            "bio": "Passionate full-stack developer. Loves open source.",
            "public_repos": 35,
            "public_gists": 5,
            "followers": 350,
            "following": 70,
            "created_at": "2015-06-09T12:45:00Z",
            "updated_at": "2025-05-14T11:00:00Z",
            "type": "User",
            "score": 0.95,
        },
    ],
    "Repositories": [
        {
            "id": 1296269,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
            "name": "Hello-World",
            "full_name": "octocat/Hello-World",
            "private": False,
            "owner": {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "type": "User",
                "site_admin": False,
            },
            "description": "My first repository on GitHub!",
            "fork": False,
            "created_at": "2011-01-26T19:01:12Z",
            "updated_at": "2025-04-20T15:30:00Z",
            "pushed_at": "2025-04-18T20:10:05Z",
            "size": 256,
            "stargazers_count": 2500,
            "watchers_count": 2500,
            "forks_count": 1800,
            "open_issues_count": 15,
            "language": "JavaScript",
            "license": {"key": "mit", "name": "MIT License", "spdx_id": "MIT"},
            "allow_forking": True,
            "is_template": False,
            "web_commit_signoff_required": False,
            "topics": ["octocat", "example", "hello-world", "github"],
            "visibility": "public",
            "default_branch": "main",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "archived": False,
            "disabled": False,
            "score": 1.0,
        },
        {
            "id": 2100015,
            "node_id": "MDEwOlJlcG9zaXRvcnkyMTAwMDE1",
            "name": "ai-project-alpha",
            "full_name": "devjane/ai-project-alpha",
            "private": True,
            "owner": {
                "login": "devjane",
                "id": 25,
                "node_id": "MDQ6VXNlcjI1",
                "type": "User",
                "site_admin": False,
            },
            "description": "Alpha version of an exciting AI project.",
            "fork": False,
            "created_at": "2023-02-10T09:30:00Z",
            "updated_at": "2025-05-12T18:00:00Z",
            "pushed_at": "2025-05-12T17:55:00Z",
            "size": 10240,
            "stargazers_count": 5,
            "watchers_count": 5,
            "forks_count": 0,
            "open_issues_count": 3,
            "language": "Python",
            "license": None,
            "allow_forking": False,
            "is_template": False,
            "web_commit_signoff_required": True,
            "topics": ["ai", "machine-learning", "python", "research"],
            "visibility": "private",
            "default_branch": "develop",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "archived": False,
            "disabled": False,
            "score": 0.89,
        },
    ],
    "Issues": [
        {
            "id": 789,
            "node_id": "MDU6SXNzdWU3ODk=",
            "number": 1,
            "repo_full_name": "octocat/Hello-World",
            "title": "Documentation unclear on setup",
            "user": {
                "login": "devjane",
                "id": 25,
                "node_id": "MDQ6VXNlcjI1",
                "type": "User",
                "site_admin": False,
            },
            "labels": [
                {
                    "id": 208045947,
                    "node_id": "MDU6TGFiZWwyMDgwNDU5NDc=",
                    "name": "documentation",
                    "color": "0075ca",
                    "description": "Improvements or additions to documentation",
                    "default": True,
                },
                {
                    "id": 208045948,
                    "node_id": "MDU6TGFiZWwyMDgwNDU5NDg=",
                    "name": "help wanted",
                    "color": "008672",
                    "description": "Extra attention is needed",
                    "default": False,
                },
            ],
            "state": "open",
            "locked": False,
            "assignee": {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "type": "User",
                "site_admin": False,
            },
            "assignees": [
                {
                    "login": "octocat",
                    "id": 1,
                    "node_id": "MDQ6VXNlcjE=",
                    "type": "User",
                    "site_admin": False,
                }
            ],
            "milestone": {
                "id": 1002604,
                "node_id": "MDk6TWlsZXN0b25lMTAwMjYwNA==",
                "number": 3,
                "title": "Sprint 2.1 Docs Update",
                "description": "Tasks for improving documentation in Sprint 2.1",
                "creator": {
                    "login": "octocat",
                    "id": 1,
                    "node_id": "MDQ6VXNlcjE=",
                    "type": "User",
                    "site_admin": False,
                },
                "open_issues": 2,
                "closed_issues": 5,
                "state": "open",
                "created_at": "2025-04-01T10:00:00Z",
                "updated_at": "2025-04-05T11:00:00Z",
                "closed_at": None,
                "due_on": "2025-05-30T23:59:59Z",
            },
            "comments": 1,
            "created_at": "2025-04-10T14:22:05Z",
            "updated_at": "2025-04-11T09:10:15Z",
            "closed_at": None,
            "body": "The README.md file is missing detailed instructions for setting up the development environment on Windows.",
            "author_association": "CONTRIBUTOR",
            "active_lock_reason": None,
            "reactions": {
                "total_count": 2,
                "+1": 2,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 1,
            },
            "score": 0.92,
        },
        {
            "id": 790,
            "node_id": "MDU6SXNzdWU3OTA=",
            "number": 42,
            "repo_full_name": "devjane/ai-project-alpha",
            "title": "Model accuracy drops with new dataset",
            "user": {
                "login": "devjane",
                "id": 25,
                "node_id": "MDQ6VXNlcjI1",
                "type": "User",
                "site_admin": False,
            },
            "labels": [
                {
                    "id": 208045946,
                    "node_id": "MDU6TGFiZWwyMDgwNDU5NDY=",
                    "name": "bug",
                    "color": "d73a4a",
                    "description": "Something isn't working",
                    "default": True,
                }
            ],
            "state": "closed",
            "locked": True,
            "active_lock_reason": "resolved",
            "assignee": None,
            "assignees": [],
            "milestone": None,
            "comments": 5,
            "created_at": "2024-12-01T10:00:00Z",
            "updated_at": "2025-01-15T11:30:00Z",
            "closed_at": "2025-01-15T11:30:00Z",
            "body": "After ingesting the new dataset 'data_v3.csv', the model's prediction accuracy on the test set dropped by 15%.",
            "author_association": "OWNER",
            "reactions": {
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0,
            },
            "score": 0.75,
        },
    ],
    "IssueComments": [
        {
            "id": 12345,
            "node_id": "MDEyOklzc3VlQ29tbWVudDEyMzQ1",
            "issue_number": 1,
            "repo_full_name": "octocat/Hello-World",
            "user": {"login": "octocat", "id": 1},
            "created_at": "2025-04-11T09:10:15Z",
            "updated_at": "2025-04-11T09:10:15Z",
            "author_association": "OWNER",
            "body": "Thanks @devjane, I'll update the README with Windows-specific instructions soon.",
        }
    ],
    "PullRequests": [
        {
            "id": 456,
            "node_id": "MDExOlB1bGxSZXF1ZXN0NDU2",
            "number": 2,
            "repo_full_name": "octocat/Hello-World",
            "title": "Feature: Add dark mode toggle",
            "user": {
                "login": "devjane",
                "id": 25,
                "node_id": "MDQ6VXNlcjI1",
                "type": "User",
                "site_admin": False,
            },
            "labels": [
                {
                    "id": 67890,
                    "node_id": "MDU6TGFiZWw2Nzg5MA==",
                    "name": "enhancement",
                    "color": "a2eeef",
                    "description": "New feature or request",
                    "default": True,
                }
            ],
            "state": "open",
            "locked": False,
            "assignee": {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "type": "User",
                "site_admin": False,
            },
            "assignees": [
                {
                    "login": "octocat",
                    "id": 1,
                    "node_id": "MDQ6VXNlcjE=",
                    "type": "User",
                    "site_admin": False,
                }
            ],
            "milestone": None,
            "created_at": "2025-05-01T11:00:00Z",
            "updated_at": "2025-05-02T15:30:00Z",
            "closed_at": None,
            "merged_at": None,
            "body": "This PR introduces a dark mode toggle switch for the main interface. Includes CSS updates and a JS controller.",
            "author_association": "CONTRIBUTOR",
            "draft": False,
            "merged": False,
            "mergeable": True,
            "rebaseable": True,
            "mergeable_state": "clean",
            "merged_by": None,
            "comments": 1,
            "review_comments": 2,
            "commits": 3,
            "additions": 250,
            "deletions": 30,
            "changed_files": 5,
            "head": {
                "label": "devjane:feature-dark-mode",
                "ref": "feature-dark-mode",
                "sha": "abcdef1234567890abcdef1234567890abcdef12",
                "user": {
                    "login": "devjane",
                    "id": 25,
                    "node_id": "MDQ6VXNlcjI1",
                    "type": "User",
                    "site_admin": False,
                },
                "repo": {
                    "id": 123457,
                    "node_id": "MDEwOlJlcG9zaXRvcnkxMjM0NTc=",
                    "name": "Hello-World-Fork-DevJane",
                    "full_name": "devjane/Hello-World-Fork-DevJane",
                    "private": False,
                    "owner": {
                        "login": "devjane",
                        "id": 25,
                        "node_id": "MDQ6VXNlcjI1",
                        "type": "User",
                        "site_admin": False,
                    },
                    "description": "Fork for dark mode feature",
                    "fork": True,
                    "created_at": "2025-04-28T10:00:00Z",
                    "updated_at": "2025-05-01T09:00:00Z",
                    "pushed_at": "2025-05-01T09:00:00Z",
                    "size": 260,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": "JavaScript",
                    "has_issues": False,
                    "has_projects": False,
                    "has_downloads": True,
                    "has_wiki": False,
                    "has_pages": False,
                    "forks_count": 0,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 0,
                    "license": None,
                    "allow_forking": True,
                    "is_template": False,
                    "web_commit_signoff_required": False,
                    "topics": [],
                    "visibility": "public",
                    "default_branch": "main",
                },
            },
            "base": {
                "label": "octocat:main",
                "ref": "main",
                "sha": "0987654321fedcba0987654321fedcba09876543",
                "user": {
                    "login": "octocat",
                    "id": 1,
                    "node_id": "MDQ6VXNlcjE=",
                    "type": "User",
                    "site_admin": False,
                },
                "repo": {
                    "id": 1296269,
                    "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
                    "name": "Hello-World",
                    "full_name": "octocat/Hello-World",
                    "private": False,
                    "owner": {
                        "login": "octocat",
                        "id": 1,
                        "node_id": "MDQ6VXNlcjE=",
                        "type": "User",
                        "site_admin": False,
                    },
                    "description": "My first repository on GitHub!",
                    "fork": False,
                    "created_at": "2011-01-26T19:01:12Z",
                    "updated_at": "2025-04-20T15:30:00Z",
                    "pushed_at": "2025-04-18T20:10:05Z",
                    "size": 256,
                    "stargazers_count": 2500,
                    "watchers_count": 2500,
                    "language": "JavaScript",
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 1800,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 15,
                    "license": {"key": "mit", "name": "MIT License", "spdx_id": "MIT"},
                    "allow_forking": True,
                    "is_template": False,
                    "web_commit_signoff_required": False,
                    "topics": ["octocat", "example", "hello-world", "github"],
                    "visibility": "public",
                    "default_branch": "main",
                },
            },
            "maintainer_can_modify": True,
        }
    ],
    "PullRequestReviewComments": [
        {
            "id": 2001,
            "node_id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDIwMDE=",
            "pull_request_review_id": 301,
            "pull_request_number": 2,
            "repo_full_name": "octocat/Hello-World",
            "user": {"login": "octocat", "id": 1},
            "body": "Nice use of CSS variables here!",
            "commit_id": "abcdef1234567890abcdef1234567890abcdef12",
            "path": "css/style.css",
            "position": 5,
            "original_position": 5,
            "diff_hunk": "@@ -10,3 +10,7 @@ body {\n   --text-color: #333;\n }\n \n+.dark-mode {\n+  --bg-color: #333;\n+  --text-color: #f0f0f0;\n+}\n\\ No newline at end of file",
            "created_at": "2025-05-02T15:30:00Z",
            "updated_at": "2025-05-02T15:30:00Z",
            "author_association": "OWNER",
            "start_line": None,
            "original_start_line": None,
            "start_side": None,
            "line": 13,
            "original_line": 13,
            "side": "RIGHT",
        }
    ],
    "PullRequestReviews": [
        {
            "id": 301,
            "node_id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzAx",
            "pull_request_number": 2,
            "repo_full_name": "octocat/Hello-World",
            "user": {"login": "octocat", "id": 1},
            "body": "Overall looks good. Just one minor suggestion about the transition effect.",
            "state": "COMMENTED",
            "commit_id": "abcdef1234567890abcdef1234567890abcdef12",
            "submitted_at": "2025-05-02T15:35:00Z",
            "author_association": "OWNER",
        }
    ],
    "Commits": [
        {
            "sha": "0987654321fedcba0987654321fedcba09876543",
            "node_id": "MDY6Q29tbWl0MTI5NjI2OTA6MDk4NzY1NDMyMWZlZGNhYmM=",
            "repo_full_name": "octocat/Hello-World",
            "commit": {
                "author": {
                    "name": "The Octocat",
                    "email": "octocat@github.com",
                    "date": "2025-04-18T20:10:00Z",
                },
                "committer": {
                    "name": "The Octocat",
                    "email": "octocat@github.com",
                    "date": "2025-04-18T20:10:00Z",
                },
                "message": "docs: update installation guide\n\nAdded more details for Linux and macOS users.",
                "tree": {"sha": "d80088554ba9f694d24749358051735439652497"},
                "comment_count": 0,
            },
            "author": {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "gravatar_id": "",
                "type": "User",
                "site_admin": False,
            },
            "committer": {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "gravatar_id": "",
                "type": "User",
                "site_admin": False,
            },
            "parents": [
                {
                    "sha": "e5a7901a71918dec165810f68759308076245678",
                    "node_id": "CNDY6UGFyZW50Q29tbWl0MTIzNDU=",
                }
            ],
            "stats": {"total": 150, "additions": 100, "deletions": 50},
            "files": [
                {
                    "sha": "1f87078a70cf908915958a0096351099e84db273",
                    "filename": "README.md",
                    "status": "modified",
                    "additions": 70,
                    "deletions": 20,
                    "changes": 90,
                    "patch": "@@ -1,5 +1,55 @@ ...",
                },
                {
                    "sha": "b45d3488c7083c716077615056fed208f081f20c",
                    "filename": "scripts/install.sh",
                    "status": "added",
                    "additions": 30,
                    "deletions": 0,
                    "changes": 30,
                    "patch": "@@ -0,0 +1,30 @@ ...",
                },
            ],
        }
    ],
    "Branches": [
        {
            "name": "main",
            "repo_full_name": "octocat/Hello-World",
            "commit": {"sha": "0987654321fedcba0987654321fedcba09876543"},
            "protected": True,
        },
        {
            "name": "feature-dark-mode",
            "repo_full_name": "devjane/Hello-World-Fork-DevJane",
            "commit": {"sha": "abcdef1234567890abcdef1234567890abcdef12"},
            "protected": False,
        },
    ],
    "BranchCreationDetailsCollection": [
        {
            "repo_full_name": "octocat/Hello-World",
            "ref": "refs/heads/new-feature-branch",
            "node_id": "MDM6UmVmcmVmcy9oZWFkcy9uZXctZmVhdHVyZS1icmFuY2g=",
            "object": {
                "type": "commit",
                "sha": "0987654321fedcba0987654321fedcba09876543",
            },
        },
        {
            "repo_full_name": "devjane/ai-project-alpha",
            "ref": "refs/heads/hotfix/bug-123",
            "node_id": "MDM6UmVmcmVmcy9oZWFkcy9ob3RmaXgvYnVnLTEyMw==",
            "object": {
                "type": "commit",
                "sha": "c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0",
            },
        },
    ],
    "PullRequestFilesCollection": [
        {
            "repo_full_name": "octocat/Hello-World",
            "pull_request_number": 2,
            "files": [
                {
                    "sha": "9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b",
                    "filename": "css/style.css",
                    "status": "modified",
                    "additions": 15,
                    "deletions": 2,
                    "changes": 17,
                    "patch": "@@ -5,2 +5,15 @@\n /* existing styles */\n+/* dark mode styles */\n+body.dark-mode {\n+  background-color: #121212;\n+  color: #e0e0e0;\n+}\n+/* more additions... */",
                },
                {
                    "sha": "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
                    "filename": "js/app.js",
                    "status": "added",
                    "additions": 55,
                    "deletions": 0,
                    "changes": 55,
                    "patch": "@@ -0,0 +1,55 @@\n+function toggleDarkMode() {\n+  // implementation\n+}\n+// event listeners etc.",
                },
                {
                    "sha": "f0e1d2c3b4a59f8e7d6c5b4a3f2e1d0c9b8a7f6e",
                    "filename": "index.html",
                    "status": "modified",
                    "additions": 5,
                    "deletions": 1,
                    "changes": 6,
                    "patch": '@@ -10,1 +10,5 @@\n-  <script src="old.js"></script>\n+  <button id="darkModeToggle">Toggle Dark Mode</button>\n+  <script src="js/app.js"></script>',
                },
            ],
        }
    ],
    "CodeSearchResultsCollection": [
        {
            "name": "app.js",
            "path": "src/js/app.js",
            "sha": "7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f",
            "repository": {
                "id": 1296269,
                "name": "Hello-World",
                "full_name": "octocat/Hello-World",
                "owner": {"login": "octocat", "id": 1},
            },
            "score": 25.8,
        },
        {
            "name": "data_processor.py",
            "path": "utils/data_processor.py",
            "sha": "c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2",
            "repository": {
                "id": 2100015,
                "name": "ai-project-alpha",
                "full_name": "devjane/ai-project-alpha",
                "owner": {"login": "devjane", "id": 25},
            },
            "score": 19.2,
        },
    ],
    "CodeScanningAlerts": [
        {
            "number": 15,
            "repo_full_name": "devjane/ai-project-alpha",
            "created_at": "2025-03-01T10:00:00Z",
            "updated_at": "2025-03-01T10:00:00Z",
            "state": "open",
            "dismissed_by": None,
            "dismissed_at": None,
            "dismissed_reason": None,
            "rule": {
                "id": "py/path-injection",
                "severity": "error",
                "description": "User-controlled data flows into a file path operation. This could allow an attacker to access arbitrary files.",
                "name": "Path Traversal",
                "full_description": "A detailed explanation of Path Traversal vulnerabilities and how they can be exploited.",
                "tags": ["security", "cwe-22"],
            },
            "tool": {
                "name": "CodeQL",
                "version": "2.16.0",
                "guid": "tool-guid-codeql-xyz-789",
            },
            "most_recent_instance": {
                "ref": "refs/heads/develop",
                "analysis_key": "py_analysis_key_dev_12345",
                "category": "Static Analysis",
                "environment": '{"language":"python", "runner":"github-actions"}',
                "state": "open",
                "commit_sha": "c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0",
                "location": {
                    "path": "src/data_processor.py",
                    "start_line": 125,
                    "end_line": 125,
                    "start_column": 15,
                    "end_column": 40,
                },
                "message": {
                    "text": "Unsanitized user input 'filename' is used to construct a file path."
                },
                "classifications": ["production"],
            },
        }
    ],
    "SecretScanningAlerts": [
        {
            "number": 7,
            "repo_full_name": "devjane/ai-project-alpha",
            "created_at": "2025-02-15T14:30:00Z",
            "state": "open",
            "secret_type": "slack_webhook_url",
            "secret_type_display_name": "Slack Webhook URL",
            "secret": "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX (redacted)",
            "resolution": None,
            "resolved_by": None,
            "resolved_at": None,
            "resolution_comment": None,
        }
    ],
    "FileContents": {
        "octocat_Hello-World_README.md_main": {
            "type": "file",
            "encoding": "base64",
            "size": 150,
            "name": "README.md",
            "path": "README.md",
            "content": "IyBIZWxsby1Xb3JsZAoKPHNwYW4+TXkgZmlyc3QgcmVwb3NpdG9yeSBvbiBHaXRIdWIhPC9zcGFuPgoK چند الفاظ اردو میں بھی۔",
            "sha": "e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5",
        },
        "devjane_ai-project-alpha_src_dir_develop": [
            {
                "type": "file",
                "size": 8192,
                "name": "main_model.py",
                "path": "src/main_model.py",
                "sha": "5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b",
            },
            {
                "type": "file",
                "size": 4096,
                "name": "data_processor.py",
                "path": "src/data_processor.py",
                "sha": "8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c",
            },
            {
                "type": "dir",
                "size": 0,
                "name": "utils",
                "path": "src/utils",
                "sha": "2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a",
            },
        ],
    },
}


def save_state(filepath: str) -> None:
    """Save the current state to a JSON file.

    Args:
        filepath: Path to save the state file.
    """
    with open(filepath, "w") as f:
        json.dump(DB, f)


# with open("git.json", "r", encoding="utf-8") as f:
#     db_data = json.load(f)
# github_db_instance = GitHubDB(**db_data)


def load_state(filepath: str) -> None:
    
    """Load state from a JSON file.

    Args:
        filepath: Path to load the state file from.
    """
    global DB
    with open(filepath, "r") as f:
        new_data = json.load(f)
        DB.clear()
        DB.update(new_data)
        
    # Ensure CurrentUser is set
    if "CurrentUser" not in DB:
        if len(DB["Users"]) > 0:
            DB["CurrentUser"] = {"id": DB["Users"][0]["id"], "login": DB["Users"][0]["login"]}
        else:
            # Create a default user if no users exist
            DB["CurrentUser"] = {"id": 1, "login": "octocat"}
            